FROM node:20-alpine as prodFrontendAngular

ENV NODE_ENV=production

ENV PORT=4200

WORKDIR /app

COPY package*.json .

RUN npm install --production

RUN npm install -g @angular/cli && npm install

COPY . .


CMD ["ng", "serve", "--host", "0.0.0.0"]
