
#stage 1, build

FROM node:20-alpine as builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build --prod


#stage 2, serve with nginx

FROM nginx:alpine


WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /app/dist/halal-eats/browser .

COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN chmod -R 755 /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

