FROM node:20-alpine as prodFrontendAngular

ENV NODE_ENV=production

ENV PORT=4200

WORKDIR /app

COPY package*.json .

RUN npm ci --omit=dev

######these should be enough but errors are popping up because ther eis no production\

#RUN npm install -g @angular/cli 

#RUN npm install rollup --omit=dev

# && npm install --production

COPY . .


CMD ["ng", "serve", "--host", "0.0.0.0"]
